### ISSUE TITLE
Error while Creating Mono cart report with Teams Webhook

### ISSUE THREAD

**Issue by animeshkumar29** [cenfun/monocart-reporter-test#1]
Hi team 

i followed all steps which is mentioned in the file , but i am getting error while running in local. so far i do not have CI/CD enabled , 

can someone please help , 

here is  error 

Error in reporter page.goto: Protocol error (Page.navigate): Cannot navigate to invalid URL
=========================== logs ===========================
navigating to "/Users/animeshkumar/Desktop/Animesh/Projecttest/Automation/TestingWorkPlace/test-results/report.html", waiting until "load"
============================================================
    at _default (/Users/animeshkumar/Desktop/Animesh/Projecttest/Automation/TestingWorkPlace/support/base/teams-webhook.js:36:16)
    at onEnd (/Users/animeshkumar/Desktop/Animesh/Projecttest/Automation/TestingWorkPlace/playwright.config.js:54:13) {
  name: 'Error'
}

i am using Mac Machine

**Comment by cenfun** [comment]
try add the file to the path
    await page.goto(`file://${path.resolve(htmlPath)}`);

**Comment by cenfun** [comment]
better solution is using `pathToFileURL`
```
import { pathToFileURL } from 'url';
const htmlUrl = pathToFileURL(path.resolve(htmlPath)).toString();
await page.goto(htmlUrl);
```
