### ISSUE TITLE
How can you collect comments data?

### ISSUE THREAD

**Issue by vittorioc98** [cenfun/monocart-reporter-test#4]
Hello!

May i ask how do you collect Comments data from tests?

Here: https://github.com/cenfun/monocart-reporter-test/blob/main/integrations/xray/xray.js, at line 57, you call `item.xray`. I suppose that this will grab the JSDoc `@xray` value. 
How can i achieve this in my custom reporter? I'd like to grab those values and use it to build a custom reporter..

Thanks a lot,
Vittorio.

**Comment by cenfun** [comment]
it required `visitor` options, see config:
https://github.com/cenfun/monocart-reporter-test/blob/main/integrations/xray/playwright.config.js#L20-L36

**Comment by vittorioc98** [comment]
Does it only work with monocart reporter? Because I have my custom one.

**Comment by cenfun** [comment]
yes, the comments data was collected by monocart reporter

**Comment by vittorioc98** [comment]
Oh ok, unlucky.
Thank you for your time.
